/*
 * Copyright (C) 2018  Nexell Co., Ltd.
 * Author: deoks <truevirtue@nexell.co.kr>
 *
 * Nexell informs that this code and information is provided "as Is" base
 * and without warranty of any kind, either expressed or implied, including,
 * but not limited to the implied warranties of merchantabulity and/or
 * fitness for a aparticular purpose.
 *
 * This program is copyrighted by Nexcel and does not allow modification or
 * distribution. In addition to the author (person in charge), the modifier
 * is responsible for the modification.
 */
#include <sysheader.h>
#include <secure.h>

struct tzinfo_reg SYS_BUSCFG[5] = {
	/* SYS_BUSCFG[0] -> BUSCFG6 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:AXIM_MDMA_0__SYSREG__TZINFO, [01]: AXIM_MP2TSI_1__SYSREG__TZINFO, [02]: AXIM_MP2TSI_0__SYSREG__TZINFO, [03]: RSVD 				*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [04]:AXIM_SSS_0__SYSREG__TZINFO,  [05]: RSVD,                          [06]: RSVD,                          [07]: AXIM_CSSYS_0__SYSREG__TZINFO	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [08]:AXIM_PDM_0__SYSREG__TZINFO,  [09]: AXIM_SDMA_1__SYSREG__TZINFO,   [10]: AXIM_SDMA_0__SYSREG__TZINFO,   [11]: AXIM_DMA_1__SYSREG__TZINFO		*/
		SECURE_ONLY, RESERVED   , RESERVED   , RESERVED   ,		/* [12]:AXIM_DMA_0__SYSREG__TZINFO,  [13:31]: RESERVED   												*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
	/* SYS_BUSCFG[1] -> BUSCFG7 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, RESERVED   ,		/* [00]:AXIM_SDMA_0__SYSREG__TZPCDECPROT,   [01]: AXIM_DMA_1__SYSREG__TZPCDECPROT,    [02]: AXIM_DMA_0__SYSREG__TZPCDECPROT,    [03]: RSVD 				*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , RESERVED   ,		/* [04]:CAN_0__SYSREG__CAN_TZPCDECPROT,     [05]: CAN_0__SYSREG__RAM_TZPCDECPROT,     [06]: RSVD,                               [07]: RSVD				*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [08]:GPIO_4__SYSREG__SECURE_TZPCDECPROT, [09]: GPIO_3__SYSREG__SECURE_TZPCDECPROT, [10]: GPIO_2__SYSREG__SECURE_TZPCDECPROT, [11]: GPIO_1__SYSREG__SECURE_TZPCDECPROT*/
		SECURE_ONLY, RESERVED   , RESERVED   , SECURE_ONLY,		/* [12]:GPIO_0__SYSREG__SECURE_TZPCDECPROT, [13]: RSVD,                               [14]: RSVD,                               [15]: GPIO_4__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [16]:GPIO_3__SYSREG__TZPCDECPROT,        [17]: GPIO_2__SYSREG__TZPCDECPROT,        [18]: GPIO_1__SYSREG__TZPCDECPROT,        [19]: GPIO_0__SYSREG__TZPCDECPROT	*/
		RESERVED   , SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [20]:RSVD,                               [21]: SMC_0__SYSREG__CFG_TZPCDECPROT,     [22]: CAN_1__SYSREG__CAN_TZPCDECPROT,	[23]: CAN_1__SYSREG__RAM_TZPCDECPROT	*/
		SECURE_ONLY, RESERVED   , SECURE_ONLY, SECURE_ONLY,		/* [24]:TMU_0__SYSREG__TZPCDECPROT,         [25]: RSVD,     			      [26]: SYSCTRLTOP_0__SYSREG__NONSECURE_TZPCDECPROT, [27]: SYSCTRLTOP_0__SYSREG__TZPCDECPROT*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [28]:ECID_0__SYSREG__SECURE_TZPCDECPROT, [29]: ECID_0__SYSREG__TZPCDECPROT,        [30]: SYSREG_SYS_0__SYSREG__SECURE_TZPCDECPROT,	[31]: SYSREG_SYS_0__SYSREG__TZPCDECPROT	*/
	},
	/* SYS_BUSCFG[2] -> BUSCFG8 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:PWM_0__SYSREG__TZPCDECPROT,         [01]:SECURE_WDT_0__SYSREG__TZPCDECPROT,   [02]: WDT_0__SYSREG__TZPCDECPROT,	        [03]: I2S_3__SYSREG__TZPCDECPROT				*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, RESERVED,		/* [04]:I2S_2__SYSREG__TZPCDECPROT,	    [05]: I2S_1__SYSREG__TZPCDECPROT,	      [06]: I2S_0__SYSREG__TZPCDECPROT,		[07]: RSVD				*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [08]:ADC_0__SYSREG__TZPCDECPROT,	    [09]: I2C_4__SYSREG__TZPCDECPROT,	      [10]: I2C_3__SYSREG__TZPCDECPROT,		[11]: I2C_2__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , SECURE_ONLY,		/* [12]:I2C_1__SYSREG__TZPCDECPROT,	    [13]: I2C_0__SYSREG__TZPCDECPROT,	      [14]: RSVD,				[15]: UART_6__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [16]:UART_5__SYSREG__TZPCDECPROT,	    [17]: UART_4__SYSREG__TZPCDECPROT,	      [18]: UART_3__SYSREG__TZPCDECPROT,	[19]: UART_2__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [20]:UART_1__SYSREG__TZPCDECPROT,	    [21]: UART_0__SYSREG__TZPCDECPROT,	      [22]: AXIM_MDMA_0__SYSREG__TZPCDECPROT,	[23]: AXIM_PDM_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , SECURE_ONLY,		/* [24]:AXIM_MP2TSI_1__SYSREG__TZPCDECPROT, [25]: AXIM_MP2TSI_0__SYSREG__TZPCDECPROT, [26]: RSVD,				[27]: AXIM_SSS_0__SYSREG__TZPCDECPROT	*/
		RESERVED   , RESERVED   , SECURE_ONLY, SECURE_ONLY,		/* [28]:RSVD, 				    [29]: RSVD,				      [30]: AXIM_CSSYS_0__SYSREG__TZPCDECPROT,	[31]: AXIM_SDMA_1__SYSREG__TZPCDECPROT	*/
	},
	/* SYS_BUSCFG[3] -> BUSCFG9 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:CMU_SRC_0__SYSREG__TZPCDECPROT,     [01]:CMU_SYS_0__SYSREG__TZPCDECPROT,      [02]: FSYS_BUS_0__SYSREG__GPV_TZPCDECPROT,[03]: DUMMY_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, RESERVED,		/* [04]:SSS_0__SYSREG__PUF_TZPCDECPROT,	    [05]: PLL_0__SYSREG__TZPCDECPROT,	      [06]: PLL_1__SYSREG__TZPCDECPROT,		[07]: RSVD				*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [08]:PDM_0__SYSREG__TZPCDECPROT,	    [09]: MP2TSI_1__SYSREG__TZPCDECPROT,      [10]: MP2TSI_0__SYSREG__TZPCDECPROT,	[11]: SPDIFRX_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , SECURE_ONLY,		/* [12]:SPDIFTX_0__SYSREG__TZPCDECPROT,	    [13]: SPI_2__SYSREG__TZPCDECPROT,	      [14]: SPI_1__SYSREG__TZPCDECPROT,		[15]: MDMA_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [16]:SDMA_1__SYSREG__TZPCDECPROT,	    [17]: SDMA_0__SYSREG__TZPCDECPROT,	      [18]: DMA_1__SYSREG__TZPCDECPROT,		[19]: DMA_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, RESERVED   ,		/* [20]:SECURE_TIMER_0__SYSREG__TZPCDECPROT,[21]: TIMER_0_SYSREG__TZPCDECPROT,	      [22]: SSS_0__SYSREG__HOST_KEYMAN_TZPCDECPROT,	[23]: RSVD			*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,		/* [24]:RSVD,				    [25]: RSVD,				      [26]: RSVD,				[27]: RSVD				*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,		/* [28]:RSVD, 				    [29]: RSVD,				      [30]: RSVD,				[31]: RSVD				*/
	},
	/* SYS_BUSCFG[4] -> BUSCFG10 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:SSS_0__SYSREG__SSS_TZPCDECPROT,     [01]:SSS_0__SYSREG__MAILBOX_TZPCDECPROT,  [02]: SSS_0__SYSREG__KEYMAN_TZPCDECPROT,	[03]: SYS_BUS_0__SYSREG__ETC_TZPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [04]:SYS_BUS_0__SYSREG__DMA_TZPROT,	    [05]: SPI_0__SYSREG__TZPCDECPROT,	      [06]: CFG_BUS_0__SYSREG__TZPCDECPROT, 	[07]: ETC_BUS_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, RESERVED   , RESERVED   , RESERVED   ,		/* [08]:DMA_BUS_0__SYSREG__TZPCDECPROT,	    [09]: RSVD,				      [10]: RSVD,				[11]: RSVD	*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,		/* [12]:RSVD,				    [13]: RSVD,				      [14]: RSVD,				[15]: RSVD	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [16]:SYS_BUS_0__SYSREG__CFG_TZPROT,	    [17]: SYS_BUS_0__SYSREG__CFG_TZPROT,      [18]: SYS_BUS_0__SYSREG__CFG_TZPROT, 	[19]: SYS_BUS_0__SYSREG__CFG_TZPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [20]:SYS_BUS_0__SYSREG__CFG_TZPROT,	    [21]: SYS_BUS_0__SYSREG__CFG_TZPROT,      [22]: SYS_BUS_0__SYSREG__CFG_TZPROT,	[23]: SYS_BUS_0__SYSREG__CFG_TZPROT			*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , RESERVED   ,		/* [24]:SYS_BUS_0__SYSREG__CFG_TZPROT,	    [25]: SYS_BUS_0__SYSREG__CFG_TZPROT,      [26]: RSVD,				[27]: RSVD				*/
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,		/* [28]:RSVD,				    [29]: RSVD, 			      [30]: RSVD,				[31]: RSVD				*/
	}
};

struct tzinfo_reg CPU_BUSCTRL[2] = {
	/* CPU_BUSCTRL[0] -> BUSCTRL0 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:AXIM_CPU_0__SYSREG__TZPCDECPROT, [01]: PLL_CPU_0__SYSREG__TZPCDECPROT, [02]: SYSREG_CPU_0__SYSREG__SECURE_TZPCDECPROT, [03]: SYSREG_CPU_0__SYSREG__TZPCDECPROT 	*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , RESERVED   ,		/* [04]:CMU_CPU_0__SYSREG__TZPCDECPROT,  [05]: CPUPMU_0__SYSREG__TZPCDECPROT,  [06:31]: RSVD 										*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
	/* CPU_BUSCTRL[1] -> BUSCTRL1 */
	{
		SECURE_ONLY, RESERVED	, RESERVED   , RESERVED   ,		/* [00]:AXIM_CPU_0__SYSREG__TZINFO, [01]: RSVD, [02]: RSVD, [03:31]: RSVD	*/
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
	},

};

struct tzinfo_reg USB_CFG_BUS_SECURE[2] = {
	/* USB_CFG_BUS_SECURE[0] -> BUS_SECURE0 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:AXIM_BLK_USB_DATA_BUS_0__SYSREG__TZPCDECPROT, [01]: BLK_USB_DATA_BUS_0__SYSREG__TZPCDECPROT, [02]: USB20HOST_0__SYSREG__OHCI_CFG_TZPCDECPROT, [03]: USB20HOST_0__SYSREG__EHCI_CFG_TZPCDECPROT 	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [04]:USB20OTG_0__SYSREG__CFG_TZPCDECPROT,	      [05]: SYSREG_USB_0__SYSREG__SECURE_TZPCDECPROT,[06]: SYSREG_USB_0__SYSREG__TZPCDECPROT,	      [07]: CMU_USB_0__SYSREG__TZPCDECPROT		*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,		/* [08:31]: RSVD */
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
	/* USB_CFG_BUS_SECURE[1] -> BUS_SECURE1 */
	{
		SECURE_ONLY, RESERVED	, RESERVED   , RESERVED   ,		/* [00]:AXIM_BLK_USB_DATA_BUS_0__SYSREG__TZINFO, [01]: BLK_USB_DATA_BUS_0__SYSREG__TZPROT, [02:31]: RSVD */
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
		RESERVED   , RESERVED	, RESERVED   , RESERVED   ,
	}
};

struct tzinfo_reg MM_BUS_SECURE[3] = {
	/* MM_BUS_SECURE[0] -> CFG_BUS0 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:CODA960_0__SYSREG__TZPCDECPROT,		    [01]: LVDS_0__SYSREG__TZPCDECPROT,			      [02]: DPC_0__SYSREG__TZPCDECPROT,				[03]: VIP_0__SYSREG__TZPCDECPROT 		*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [04]:DEINTERLACE_0__SYSREG__TZPCDECPROT,	    [05]: GZD_0__SYSREG__TZPCDECPROT,			      [06]: ROTATOR_0__SYSREG__TZPCDECPROT,			[07]: SYSREG_MM_0__SYSREG__SECURE_TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [08]:SYSREG_MM_0__SYSREG__TZPCDECPROT,	    [09]: CMU_MM_0__SYSREG__TZPCDECPROT,		      [10]: BLK_MM_DATA_BUS_0__SYSREG__GPV_TZPCDECPROT,		[11]: AXIM_ROTATOR_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [12]:AXIM_G2D_0__SYSREG__TZPCDECPROT,	    [13]: AXIM_DEINTERLACE_0__SYSREG__TZPCDECPROT,	      [14]: AXIM_DPC_0__SYSREG__TZPCDECPROT,			[15]: AXIM_VIP_0__SYSREG__TZPCDECPROT		*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [16]:AXIM_CODA960_0__SYSREG__TZPCDECPROT,	    [17]: BLK_MM_CFG_BUS_0__SYSREG__G2D_TZPCDECPROT,	      [18]: BLK_MM_CFG_BUS_0__SYSREG__G2D_TZPCDECPROT,		[19]: BLK_MM_DATA_BUS_0__SYSREG__PL301_TZPCDECPROT*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,		/* [20:31]:RSVD */
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
	/* MM_BUS_SECURE[1] -> CFG_BUS_SECURE */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:AXIM_CODA960_0__SYSREG__TZINFO, [01]: AXIM_ROTATOR_0__SYSREG__TZINFO, [02]: AXIM_G2D_0__SYSREG__TZINFO, [03]: AXIM_DEINTERLACE_0__SYSREG__TZINFO 	*/
		SECURE_ONLY, SECURE_ONLY, RESERVED   , RESERVED   ,		/* [04]:AXIM_DPC_0__SYSREG__TZINFO,	[05]: AXIM_VIP_0__SYSREG__TZINFO,[06]: RSVD,	      [07]: RSVD		*/
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,		/* [08:31]: RSVD */
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
	/* MM_BUS_SECURE[1] -> DATA_BUS */
	{
		SECURE_ONLY, RESERVED   , RESERVED   , RESERVED   ,		/* [00]:BLK_MM_DATA_BUS_0__SYSREG__PL301_0_TZPROT, [01:31]: RSVD */
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
};

struct tzinfo_reg HSIF_BUS_SECURE[2] = {
	/* HSIF_BUS_SECURE[0] -> BUSCTRL0 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:GMAC_RMII_0__SYSREG__TZPCDECPROT,		[01]: GMAC_RGMII_0__SYSREG__TZPCDECPROT,	   [02]: SDMMC_2__SYSREG__TZPCDECPROT,		[03]: SDMMC_1__SYSREG__TZPCDECPROT 	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [04]:SDMMC_0__SYSREG__TZPCDECPROT,			[05]: SYSREG_HSIF_0__SYSREG__SECURE_TZPCDECPROT,   [06]: SYSREG_HSIF_0__SYSREG__TZPCDECPROT,	[07]: RSVD,				*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [08]:NANDC_0__SYSREG__TZPCDECPROT,			[09]: AXIM_GMAC_RMII_0__SYSREG__TZPCDECPROT,	   [10]: AXIM_GMAC_RGMII_0__SYSREG__TZPCDECPROT,[11]: AXIM_NANDC_0__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [12]:BLK_HSIF_DATA_BUS_0__SYSREG__TZPCDECPROT,	[13]: BLK_HSIF_DATA_BUS_0__SYSREG__PL301_0_TZPROT, [14]: AXIM_SDMMC_2__SYSREG__TZPCDECPROT,	[15]: AXIM_SDMMC_1__SYSREG__TZPCDECPROT	*/
		SECURE_ONLY, RESERVED   , RESERVED   , RESERVED   ,		/* [16]:AXIM_SDMMC_0__SYSREG__TZPCDECPROT,	    	[17:31]: RSVD */
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
	/* HSIF_BUS_SECURE[1] -> BUSCTRL1 */
	{
		SECURE_ONLY, SECURE_ONLY, SECURE_ONLY, SECURE_ONLY,		/* [00]:AXIM_GMAC_RMII_0__SYSREG__TZINFO, [01]: AXIM_GMAC_RGMII_0__SYSREG__TZINFO. [02]: AXIM_NANDC_0__SYSREG__TZINFO, [03]: AXIM_SDMMC_2__SYSREG__TZINFO */
		SECURE_ONLY, SECURE_ONLY, RESERVED   , RESERVED   ,		/* [04]: AXIM_SDMMC_1__SYSREG__TZINFO,	  [05]: AXIM_SDMMC_0__SYSREG__TZINFO */
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
		RESERVED   , RESERVED   , RESERVED   , RESERVED   ,
	},
};


void set_tzpc(void)
{
	volatile unsigned char *base;

	base = PHY_BASEADDR_SYSREG_SYS;
	mmio_write_32(&base[0x200], SYS_BUSCFG[0]);
	mmio_write_32(&base[0x204], SYS_BUSCFG[1]);
	mmio_write_32(&base[0x208], SYS_BUSCFG[2]);
	mmio_write_32(&base[0x20C], SYS_BUSCFG[3]);
	mmio_write_32(&base[0x220], SYS_BUSCFG[4]);
	mmio_write_32(&base[0x8000], SYS_REGSECURE0);
	mmio_write_32(&base[0x8004], SYS_REGSECURE1);
	mmio_write_32(&base[0x8008], SYS_REGSECURE2);

	base = PHY_BASEADDR_SYSREG_CPU;
	mmio_write_32(&base[0x04C], CPU_BUSCTRL[0]);
	mmio_write_32(&base[0x050], CPU_BUSCTRL[1]);
	mmio_write_32(&base[0x8000], CPU_REGSECURE0);

	base = PHY_BASEADDR_SYSREG_USB;
	mmio_write_32(&base[0x100], USB_CFG_BUS_SECURE[0]);
	mmio_write_32(&base[0x104], USB_CFG_BUS_SECURE[1]);
	mmio_write_32(&base[0x8000], USB_REGSECURE0);
	mmio_write_32(&base[0x8004], USB_REGSECURE1);

	base = PHY_BASEADDR_SYSREG_MM;
	mmio_write_32(&base[0x040], MM_BUS_SECURE[0]);
	mmio_write_32(&base[0x050], MM_BUS_SECURE[1]);
	mmio_write_32(&base[0x060], MM_BUS_SECURE[2]);
	mmio_write_32(&base[0x8000], MM_REGSECURE0);
	mmio_write_32(&base[0x8004], MM_REGSECURE1);

	base = PHY_BASEADDR_SYSREG_HSIF;
	mmio_write_32(&base[0x020], HSIF_BUS_SECURE[0]);
	mmio_write_32(&base[0x030], HSIF_BUS_SECURE[1]);
	mmio_write_32(&base[0x8000], HSIF_REGSECURE0);
}

void system_set_dev_access(void)
{
	/* system default */
	set_tzpc();
}

